[package]
edition = "2021"
name = "pm-spotlight"
version = "0.1.0"

[profile.release]
strip = true

[dependencies]
dirs = "4.0.0"
fltk = "1.3.5"
phf = {version = "0.10.1", features = ["macros"]}
regex = "1.5.5"
serde = {version = "1.0.136", features = ["derive"]}
toml = "0.5.9"
walkdir = "2.3.2"
